In [46]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

In [47]:
def Sum(A,k,i,j):
    n = A.shape[0]
    E = np.eye(n)
    if i == j:
        E[i,i] = k + 1
    else:
        E[i,j] = k
    return E @ A

In [48]:
def Scale(A,k,i):
    n = A.shape[0]
    E = np.eye(n)
    E[i,i] = k
    return E @ A


In [49]:
def Interchange(A,i,j):
    n = A.shape[0]
    E = np.eye(n)
    E[i,i] = 0
    E[j,j] = 0
    E[i,j] = 1
    E[j,i] = 1
    return E @ A

In [63]:
# Group 3: David, Derick, Ean. Example 1: Three Plane intersecting in a line.
#Coefficient Matrix
A = np.array([[1,-2,1],[0,2,-8],[5,0,-5]])
print('A=',A)
# The right-hand side vector
b = np.array([[0],[8],[10]])
print('b=',b)
# Augmented Materix
M = np.hstack([A,b])
print('M=',M)

A= [[ 1 -2  1]
 [ 0  2 -8]
 [ 5  0 -5]]
b= [[ 0]
 [ 8]
 [10]]
M= [[ 1 -2  1  0]
 [ 0  2 -8  8]
 [ 5  0 -5 10]]


In [64]:
#If the coefficient matrix A is invertible (nonsingular) then we can use la.solve
X = la.solve(A,b)
print(X)

[[ 1.]
 [ 0.]
 [-1.]]
